#!/usr/bin/python

import os, sys, string

if os.getuid() != 0:
	print "Must be run as root"
	sys.exit(1)

if len(sys.argv) < 3:
	print "Usage: constructor-translation-include minttool language"
	sys.exit(1)

tool = sys.argv[1]
language = sys.argv[2]

if not os.path.exists("/usr/lib/" + tool):
	print "Tool /usr/lib/" + tool + " does not exist"
	sys.exit(1)

if not os.path.exists(language + ".po"): 
	print "No language file found: " + language + ".po"
	sys.exit(1)

print "tool: " + tool
print "language: " + language

os.system("mkdir -p /usr/lib/" + tool + "/locale/" + language + "/LC_MESSAGES")
os.system("mv " + language + ".po /usr/lib/" + tool + "/locale/" + language + "/LC_MESSAGES/messages.po")
os.chdir("/usr/lib/" + tool + "/locale/" + language + "/LC_MESSAGES/")
os.system("msgfmt messages.po")

cmd = string.lower(tool)
if (cmd == "mintupload"):
	os.system("LANGUAGE=" + language + " " + cmd + " " + "/etc/linuxmint/info")
else:	
	if (cmd != "mintsystem"):
		os.system("LANGUAGE=" + language + " " + cmd)

